default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: admin
  host: localhost

development:
  <<: *default
  database: memo_development

test:
  <<: *default
  database: memo_test

production:
  <<: *default
  database: memo_production